WITH HORAS AS (
    SELECT SEQ4() AS HORA_M
    FROM TABLE(GENERATOR(ROWCOUNT => 24))
),
DIAS AS (
    SELECT COLUMN1 AS DIA_ORDEN, COLUMN2 AS DIA_NOMBRE
    FROM (VALUES 
        (1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), 
        (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo'))
)
,
VENTAS_MAPEADAS AS (
    SELECT 
        V.GEOG_LOCL_ID,
        DAYOFWEEKISO(V.TIEM_DIA_ID) AS DIA_ORDEN,
        LH.HORA_HORA_COD AS HORA_24H,
        SUM(V.VNTA_IMPORTE_CON_IVA) AS VENTA_ACUMULADA
    FROM 
        MSTRDB.DWH.FT_VENTAS AS V
        INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON V.TICKET = FFM.TICKET AND FFM.FDLN_MOVT_TIPO = 'RP'
        INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS L ON FFM.GEOG_LOCL_ID = L.GEOG_LOCL_ID AND L.GEOG_UNNG_ID = 2
        INNER JOIN MSTRDB.DWH.LU_HORA_HORA AS LH ON V.HORA_HORA_ID = LH.HORA_HORA_ID
    WHERE V.TIEM_DIA_ID >= DATEADD(DAY, -30, CURRENT_DATE - 1)
    GROUP BY ALL
) 

,
LOCALES_CON_ACTIVIDAD AS (
    SELECT 
        L.GEOG_LOCL_ID,
        L.GEOG_LOCL_COD AS LOCAL,
        D.GEOG_DPTO_DESC AS DEPARTAMENTO,
        L.GEOG_LOCL_DESC AS NOMBRE_LOCAL
    FROM MSTRDB.DWH.LU_GEOG_LOCAL L
    INNER JOIN MSTRDB.DWH.LU_GEOG_DEPTO D ON L.GEOG_DPTO_ID = D.GEOG_DPTO_ID
    WHERE L.GEOG_UNNG_ID = 2
      AND L.GEOG_LOCL_ACTIVO = 1
      AND LTRIM(TRIM(L.GEOG_LOCL_COD::VARCHAR), '0') != '10'
      AND L.GEOG_LOCL_ID IN (SELECT DISTINCT GEOG_LOCL_ID FROM VENTAS_MAPEADAS)
) 

,
ESQUELETO AS (
    SELECT * FROM LOCALES_CON_ACTIVIDAD CROSS JOIN DIAS CROSS JOIN HORAS
) 

SELECT 
    E.LOCAL,
    E.DEPARTAMENTO,
    E.NOMBRE_LOCAL,
    E.DIA_NOMBRE AS DIA_SEMANA,
    E.HORA_M AS HORA_24H,
    ROUND(COALESCE(V.VENTA_ACUMULADA, 0), 0) AS VENTAS_PESOS
FROM ESQUELETO E
LEFT JOIN VENTAS_MAPEADAS V 
    ON E.GEOG_LOCL_ID = V.GEOG_LOCL_ID 
    AND E.DIA_ORDEN = V.DIA_ORDEN 
    AND E.HORA_M = V.HORA_24H
ORDER BY E.LOCAL, E.DIA_ORDEN, E.HORA_M