WITH TICKETS_FIDELIZADOS AS (
    SELECT 
        YEAR(FFM.TIEM_DIA_ID) ANIO,
        MONTH(FFM.TIEM_DIA_ID) MES,
        COUNT(DISTINCT(FFM.TICKET)) AS TICKETS_FIDELIZADOS
    FROM 
        MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM 
        JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LG ON FFM.GEOG_LOCL_ID = LG.GEOG_LOCL_ID AND LG.GEOG_UNNG_ID = 2 AND FFM.FDLN_MOVT_TIPO = 'RP'
    WHERE 
        FFM.TIEM_DIA_ID BETWEEN DATE_TRUNC(MONTH, DATEADD(MONTH, -23, CURRENT_DATE - 1)) AND LAST_DAY(DATEADD(MONTH, -1, CURRENT_DATE - 1))
    GROUP BY
        ALL
    ORDER BY
        1, 2
    ) 
    ,
    
    TICKETS_TATA AS (
    SELECT 
        YEAR(FT.TIEM_DIA_ID) ANIO,
        MONTH(FT.TIEM_DIA_ID) MES,
        COUNT(DISTINCT(FT.TICKET)) AS TICKETS_TATA
    FROM 
        MSTRDB.DWH.FT_VENTAS AS FT
        JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LG ON FT.GEOG_LOCL_ID = LG.GEOG_LOCL_ID AND LG.GEOG_UNNG_ID = 2
    WHERE 
        FT.TIEM_DIA_ID BETWEEN DATE_TRUNC(MONTH, DATEADD(MONTH, -23, CURRENT_DATE - 1)) AND LAST_DAY(DATEADD(MONTH, -1, CURRENT_DATE - 1))
    GROUP BY
        ALL
    ORDER BY
        1, 2
    ) 

    SELECT
        A.ANIO,
        A.MES,
        ROUND((TICKETS_FIDELIZADOS / TICKETS_TATA) * 100, 2) AS REPRESENTACION
    FROM
        TICKETS_TATA AS A
        INNER JOIN TICKETS_FIDELIZADOS AS B ON A.ANIO = B.ANIO AND A.MES = B.MES
    ORDER BY
        1,
        2;