WITH DATA AS (
    SELECT
        LDC.LOCAL,
        LDC.GEOG_LOCL_DESC,
        LDC.SOCI_SOCI_ID,
        CC.CLASIFICACION_SOCIO
    FROM
        SANDBOX_PLUS.DWH.COMPORTAMENTAL_CLIENTES AS CC
        INNER JOIN SANDBOX_PLUS.DWH.LOCAL_DOMINANTE_CLIENTES AS LDC ON CC.SOCIO = LDC.SOCI_SOCI_ID
    ORDER BY
        1,
        4
)

SELECT
    LOCAL,
    GEOG_LOCL_DESC,
    CLASIFICACION_SOCIO,
    COUNT(DISTINCT(SOCI_SOCI_ID)) SOCIOS
FROM
    DATA
GROUP BY
    ALL
ORDER BY
    1,3;