WITH Periodos AS (
    SELECT
        DATEADD(DAY, -30, CURRENT_DATE - 1) AS INICIO_PERIODO_ACTUAL,
        CURRENT_DATE() - 1 AS FIN_PERIODO_ACTUAL,
        DATEDIFF(DAY, INICIO_PERIODO_ACTUAL, FIN_PERIODO_ACTUAL),

        DATEADD(YEAR, -1, INICIO_PERIODO_ACTUAL) AS INICIO_PERIODO_ANTERIOR,
        DATEADD(YEAR, -1, FIN_PERIODO_ACTUAL) AS FIN_PERIODO_ANTERIOR,
        DATEDIFF(DAY, INICIO_PERIODO_ANTERIOR, FIN_PERIODO_ANTERIOR)

) --SELECT * FROM PERIODOS;
,
MetricasPorPeriodo AS (
    SELECT
        LOC.GEOG_LOCL_COD,
        LOC.GEOG_LOCL_DESC,
        D.DEPT_NAME,
        CLA.CLASS_NAME,
        SB.SUB_NAME,
        SUM(CASE WHEN V.TIEM_DIA_ID BETWEEN P.INICIO_PERIODO_ACTUAL AND P.FIN_PERIODO_ACTUAL THEN V.VNTA_IMPORTE_SIN_IVA ELSE 0 END) AS VENTAS_ACTUAL,
        COUNT(DISTINCT CASE WHEN V.TIEM_DIA_ID BETWEEN P.INICIO_PERIODO_ACTUAL AND P.FIN_PERIODO_ACTUAL THEN MOV.SOCI_SOCI_ID END) AS CLIENTES_ACTUAL,
        SUM(CASE WHEN V.TIEM_DIA_ID BETWEEN P.INICIO_PERIODO_ANTERIOR AND P.FIN_PERIODO_ANTERIOR THEN V.VNTA_IMPORTE_SIN_IVA ELSE 0 END) AS VENTAS_ANTERIOR,
        COUNT(DISTINCT CASE WHEN V.TIEM_DIA_ID BETWEEN P.INICIO_PERIODO_ANTERIOR AND P.FIN_PERIODO_ANTERIOR THEN MOV.SOCI_SOCI_ID END) AS CLIENTES_ANTERIOR,
        GZL.GEOG_ZONA_LOCAL_DESC AS REGION,
        GTL.GEOG_TLOC_DESC AS CLUSTER
    FROM
        MSTRDB.DWH.FT_VENTAS V
        INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS MOV ON V.TICKET = MOV.TICKET
        INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL LOC ON V.GEOG_LOCL_ID = LOC.GEOG_LOCL_ID
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO ART ON V.ARTC_ARTC_ID = ART.ARTC_ARTC_ID
        INNER JOIN MSTRDB.DWH.ITEM_MASTER IM ON ART.ORIN = IM.ITEM
        INNER JOIN MSTRDB.DWH.DEPS AS D ON IM.DEPT = D.DEPT
        INNER JOIN MSTRDB.DWH.CLASS AS CLA ON IM.CLASE = CLA.CLASE
        INNER JOIN MSTRDB.DWH.SUBCLASS AS SB ON IM.SUBCLASE = SB.SUBCLASE
        INNER JOIN MSTRDB.DWH.LU_GEOG_ZONA_LOCAL AS GZL ON LOC.GEOG_ZONA_LOCAL_ID = GZL.GEOG_ZONA_LOCAL_ID
        LEFT JOIN MSTRDB.DWH.LU_GEOG_TIPO_LOCAL AS GTL ON LOC.GEOG_TLOC_ID = GTL.GEOG_TLOC_ID
        CROSS JOIN Periodos P
    WHERE
        LOC.GEOG_UNNG_ID = 2
        AND (
            (V.TIEM_DIA_ID BETWEEN P.INICIO_PERIODO_ACTUAL AND P.FIN_PERIODO_ACTUAL) OR
            (V.TIEM_DIA_ID BETWEEN P.INICIO_PERIODO_ANTERIOR AND P.FIN_PERIODO_ANTERIOR)
        )
        AND CLA.CLASS_NAME != 'PROMOCIONES'
    GROUP BY
        ALL
) --SELECT * FROM MetricasPorPeriodo ORDER BY GEOG_LOCL_COD, DEPT_NAME, CLASS_NAME;

SELECT
    GEOG_LOCL_COD,
    GEOG_LOCL_DESC,
    DEPT_NAME,
    CLASS_NAME,
    SUB_NAME,
    ROUND(VENTAS_ACTUAL, 1) AS VENTAS_ACTUAL,
    ROUND(VENTAS_ANTERIOR, 1) AS VENTAS_ANTERIOR,
    ROUND((VENTAS_ACTUAL / NULLIF(VENTAS_ANTERIOR, 0) -1), 2) AS VARIACION_VENTAS_PORC,
    CLIENTES_ACTUAL,
    CLIENTES_ANTERIOR,
    ROUND((CLIENTES_ACTUAL / NULLIF(CLIENTES_ANTERIOR, 0) - 1), 2) AS VARIACION_CLIENTES_PORC,
    REGION,
    CLUSTER
FROM
    MetricasPorPeriodo
WHERE
    VENTAS_ACTUAL > 0 OR VENTAS_ANTERIOR > 0
ORDER BY
    DEPT_NAME,
    CLASS_NAME,
    SUB_NAME;