WITH PARAMS AS (

    SELECT
        DATEADD('MONTH', -1, CURRENT_DATE()) AS INICIO_TY,
        CURRENT_DATE - 1 AS FIN_TY,
        DATEADD('YEAR', -1, INICIO_TY) AS INICIO_LY,
        DATEADD('YEAR', -1, FIN_TY) AS FIN_LY
        
) --SELECT * FROM PARAMS;
,

TICKETS_LM_TY AS (

    SELECT
        LGL.GEOG_LOCL_COD AS LOCAL,
        LGL.GEOG_LOCL_DESC AS DESC_LOCAL,
        FV.TICKET,
        CASE
            WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FFM.TICKET
            ELSE NULL
        END AS TICKET_FIDELIZADO,
        SUM(
            CASE WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FV.VNTA_IMPORTE_SIN_IVA
            ELSE 0 END
        ) AS TOTAL_VENTA_FIDELIZADA,
        SUM(FV.VNTA_IMPORTE_SIN_IVA) AS TOTAL_VENTA_TATA,
        CASE
            WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FFM.SOCI_SOCI_ID
            ELSE NULL
        END AS SOCIO,
        SUM(
            CASE
                WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FV.VNTA_IMPORTE_SIN_IVA - (FV.VNTA_UNIDADES * FV.VNTA_COSTO_PROM_POND)
                ELSE 0
            END
        ) AS GB1_FIDELIZADO,
        SUM(
            CASE
                WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FV.VNTA_UNIDADES
                ELSE 0
            END
        ) AS UNIDADES_TICKET_FIDELIZADA
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FV.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
        LEFT JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON FV.TICKET = FFM.TICKET AND FFM.FDLN_MOVT_TIPO = 'RP'
        JOIN PARAMS AS P
    WHERE
        LGL.GEOG_UNNG_ID = 2
        AND FV.TIEM_DIA_ID BETWEEN P.INICIO_TY AND P.FIN_TY
    GROUP BY
        ALL

) --SELECT * FROM TICKETS_LM_TY;
,
VENTAS_LM_TY AS (

    SELECT
        LOCAL,
        DESC_LOCAL,
        COUNT(DISTINCT(SOCIO)) AS SOCIOS_CONSUMIDORES_LM_TY,
        COUNT(DISTINCT(TICKET)) AS TICKETS_LM_TY,
        COUNT(DISTINCT(TICKET_FIDELIZADO)) AS TICKETS_FIDELIZADOS_LM_TY,
        ROUND((TICKETS_FIDELIZADOS_LM_TY / TICKETS_LM_TY) * 100, 2) AS PORC_TICK_FIDEL_TOTAL_TY,
        --SUM(TOTAL_VENTA_GRAL) AS VENTA_GENERAL_LM_TY,
        SUM(TOTAL_VENTA_FIDELIZADA) AS VENTA_FIDELIZADA_LM_TY,
        ROUND(SUM(GB1_FIDELIZADO), 2) AS TOTAL_GB1_LM_TY,
        ROUND((SUM(UNIDADES_TICKET_FIDELIZADA) / TICKETS_FIDELIZADOS_LM_TY), 2) AS UPT_25
    FROM
        TICKETS_LM_TY
    GROUP BY
        ALL
    ORDER BY
        LOCAL

) --SELECT * FROM VENTAS_LM_TY;
,
TICKETS_LM_LY AS (

    SELECT
        LGL.GEOG_LOCL_COD AS LOCAL,
        LGL.GEOG_LOCL_DESC AS DESC_LOCAL,
        FV.TICKET,
        CASE
            WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FFM.TICKET
            ELSE NULL
        END AS TICKET_FIDELIZADO,
        SUM(
            CASE WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FV.VNTA_IMPORTE_SIN_IVA
            ELSE 0 END
        ) AS TOTAL_VENTA_FIDELIZADA,
        CASE
            WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FFM.SOCI_SOCI_ID
            ELSE NULL
        END AS SOCIO,
        SUM(
            CASE
                WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FV.VNTA_IMPORTE_SIN_IVA - (FV.VNTA_UNIDADES * FV.VNTA_COSTO_PROM_POND)
                ELSE 0
            END
        ) AS GB1_FIDELIZADO,
        SUM(
            CASE
                WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FV.VNTA_UNIDADES
                ELSE 0
            END
        ) AS UNIDADES_TICKET_FIDELIZADA
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FV.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
        LEFT JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON FV.TICKET = FFM.TICKET
        JOIN PARAMS AS P
    WHERE
        LGL.GEOG_UNNG_ID = 2
        AND FV.TIEM_DIA_ID BETWEEN P.INICIO_LY AND P.FIN_LY
    GROUP BY
        ALL

) --SELECT * FROM TICKETS_LM_LY;
,
VENTAS_LM_LY AS (

    SELECT
        LOCAL,
        DESC_LOCAL,
        COUNT(DISTINCT(SOCIO)) AS SOCIOS_CONSUMIDORES_LM_LY, -- 
        COUNT(DISTINCT(TICKET)) AS TICKETS_LM_LY,
        COUNT(DISTINCT(TICKET_FIDELIZADO)) AS TICKETS_FIDELIZADOS_LM_LY, 
        ROUND((TICKETS_FIDELIZADOS_LM_LY / TICKETS_LM_LY) * 100, 2) AS PORC_TICK_FIDEL_TOTAL_LY,
        --SUM(TOTAL_VENTA_GRAL) AS VENTA_GENERAL_LM_TY,
        SUM(TOTAL_VENTA_FIDELIZADA) AS VENTA_FIDELIZADA_LM_LY,
        ROUND(SUM(GB1_FIDELIZADO), 2) AS TOTAL_GB1_LM_LY,
        ROUND((SUM(UNIDADES_TICKET_FIDELIZADA) / TICKETS_FIDELIZADOS_LM_LY), 2) AS UPT_24
    FROM
        TICKETS_LM_LY
    GROUP BY
        ALL
    ORDER BY
        LOCAL

) --SELECT * FROM VENTAS_LM_LY;
,

COMPARACION AS (

    SELECT
        A.LOCAL,
        A.DESC_LOCAL,
        A.SOCIOS_CONSUMIDORES_LM_TY, -- 20187
        ROUND((((A.SOCIOS_CONSUMIDORES_LM_TY / B.SOCIOS_CONSUMIDORES_LM_LY) -1 ) * 100), 3) AS VAR_SOCIOS_25_VS_24,
        A.TICKETS_LM_TY,
        ROUND((((A.TICKETS_LM_TY / B.TICKETS_LM_LY) -1 ) * 100), 3) AS VAR_TICKET_25_VS_24,
        A.TICKETS_FIDELIZADOS_LM_TY,
        ROUND((((A.TICKETS_FIDELIZADOS_LM_TY / B.TICKETS_FIDELIZADOS_LM_LY) -1 ) * 100), 3) AS VAR_TICKET_FIDEL_25_VS_24,
        A.PORC_TICK_FIDEL_TOTAL_TY,
        ROUND((((A.PORC_TICK_FIDEL_TOTAL_TY / B.PORC_TICK_FIDEL_TOTAL_LY) -1 ) * 100), 3) AS VAR_PORC_FIDEL_25_VS_24,
        A.VENTA_FIDELIZADA_LM_TY AS TOTAL_VTAS_FIDELIZADAS_TY,
        ROUND((((A.VENTA_FIDELIZADA_LM_TY / B.VENTA_FIDELIZADA_LM_LY) -1 ) * 100), 3) AS VAR_VTAS_25_VS_24,
        A.UPT_25,
        ROUND((((A.UPT_25 / B.UPT_24) -1 ) * 100), 3) AS VAR_UPT_25_VS_24
    FROM
        VENTAS_LM_TY AS A
        LEFT JOIN VENTAS_LM_LY AS B ON A.LOCAL = B.LOCAL
    ORDER BY
        A.LOCAL

)  --SELECT * FROM COMPARACION; --TABLERO DE COMPARACION DE VARIOS INDICADORES POR SUCURSAL
,
DETALLADO_CLIENTES_TATA AS (

    SELECT
        FV.GEOG_LOCL_ID,
        FORM.GRUPO,
        FV.TIEM_DIA_ID,
        FFM.SOCI_SOCI_ID AS SOCIO,
        FV.TICKET,
        FV.ARTC_ARTC_ID,
        CLA.CLASE,
        CLA.CLASS_NAME,
        SB.SUBCLASE,
        SB.SUB_NAME,
        FV.VNTA_IMPORTE_SIN_IVA AS VENTAS,
        SUM(FV.VNTA_IMPORTE_SIN_IVA) - SUM(FV.VNTA_UNIDADES * FV.VNTA_COSTO_PROM_POND) AS GB1
    FROM
        MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM
        INNER JOIN MSTRDB.DWH.FT_VENTAS AS FV ON FFM.TICKET = FV.TICKET
        INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FFM.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        INNER JOIN MSTRDB.DWH.ITEM_MASTER AS IM ON LAA.ORIN = IM.ITEM
        INNER JOIN MSTRDB.DWH.SUBCLASS AS SB ON IM.SUBCLASE = SB.SUBCLASE
        INNER JOIN MSTRDB.DWH.CLASS AS CLA ON IM.CLASE = CLA.CLASE
        LEFT JOIN SANDBOX_PLUS.DWH.FORMATO_LOCALES_CON_LCL_ID AS FORM ON FV.GEOG_LOCL_ID = FORM.GEOG_LOCL_ID
        JOIN PARAMS AS P
    WHERE
        LGL.GEOG_UNNG_ID = 2
        AND FFM.TIEM_DIA_ID BETWEEN P.INICIO_TY AND P.FIN_TY
        AND FV.ARTC_ARTC_ID NOT IN (SELECT DISTINCT ARTC_ARTC_ID FROM MSTRDB.DWH.LU_ARTC_ARTICULO WHERE ARTC_ARTC_COD IN ('399001000'))
    GROUP BY
        ALL
    ORDER BY
        TICKET

),

DETALLADO_CLIENTES_TATA_24 AS (

    SELECT
        FV.GEOG_LOCL_ID,
        FORM.GRUPO,
        FV.TIEM_DIA_ID,
        FFM.SOCI_SOCI_ID AS SOCIO,
        FV.TICKET,
        FV.ARTC_ARTC_ID,
        CLA.CLASE,
        CLA.CLASS_NAME,
        SB.SUBCLASE,
        SB.SUB_NAME,
        FV.VNTA_IMPORTE_SIN_IVA AS VENTAS,
        SUM(FV.VNTA_IMPORTE_SIN_IVA) - SUM(FV.VNTA_UNIDADES * FV.VNTA_COSTO_PROM_POND) AS GB1
    FROM
        MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM
        INNER JOIN MSTRDB.DWH.FT_VENTAS AS FV ON FFM.TICKET = FV.TICKET
        INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FFM.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        INNER JOIN MSTRDB.DWH.ITEM_MASTER AS IM ON LAA.ORIN = IM.ITEM
        INNER JOIN MSTRDB.DWH.SUBCLASS AS SB ON IM.SUBCLASE = SB.SUBCLASE
        INNER JOIN MSTRDB.DWH.CLASS AS CLA ON IM.CLASE = CLA.CLASE
        LEFT JOIN SANDBOX_PLUS.DWH.FORMATO_LOCALES_CON_LCL_ID AS FORM ON FV.GEOG_LOCL_ID = FORM.GEOG_LOCL_ID
        JOIN PARAMS AS P
    WHERE
        LGL.GEOG_UNNG_ID = 2
        AND FFM.TIEM_DIA_ID BETWEEN P.INICIO_LY AND P.FIN_LY
        AND FV.ARTC_ARTC_ID NOT IN (SELECT DISTINCT ARTC_ARTC_ID FROM MSTRDB.DWH.LU_ARTC_ARTICULO WHERE ARTC_ARTC_COD IN ('399001000'))
    GROUP BY
        ALL
    ORDER BY
        TICKET

)

SELECT
    A.TOTAL_CLIENTES_TY,
    B.TOTAL_CLIENTES_LY,
    (A.TOTAL_CLIENTES_TY / NULLIF(B.TOTAL_CLIENTES_LY, 0) - 1) AS VARIACION_TY_VS_LY,
    A.TOTAL_VENTA_FIDELIZADA_TY,
    B.TOTAL_VENTA_FIDELIZADA_LY,
    (A.TOTAL_VENTA_FIDELIZADA_TY / NULLIF(B.TOTAL_VENTA_FIDELIZADA_LY, 0) - 1) AS VARIACION_TY_VS_LY_VF,
    A.TOTAL_TICKETS_FIDELIZADOS,
    A.TOTAL_TICKETS_TATA,
    (A.TOTAL_TICKETS_FIDELIZADOS / NULLIF(A.TOTAL_TICKETS_TATA, 0)) AS PARTICIPACION_TICK_FID_SOB_TOT,
    C.TICKET_PROMEDIO_FIDELIZADO_TY,
    D.TICKET_PROMEDIO_FIDELIZADO_LY,
    (C.TICKET_PROMEDIO_FIDELIZADO_TY / NULLIF(D.TICKET_PROMEDIO_FIDELIZADO_LY, 0) - 1) AS VAR_TICK_PROM
FROM
    (SELECT COUNT(DISTINCT(SOCIO)) AS TOTAL_CLIENTES_TY, 
            SUM(TOTAL_VENTA_FIDELIZADA) AS TOTAL_VENTA_FIDELIZADA_TY,
            SUM(TOTAL_VENTA_TATA) AS TOTAL_VENTAS_TATA_TY,
            COUNT(DISTINCT(TICKET_FIDELIZADO)) AS TOTAL_TICKETS_FIDELIZADOS,
            COUNT(DISTINCT(TICKET)) AS TOTAL_TICKETS_TATA
    FROM 
        TICKETS_LM_TY) AS A,
    (SELECT COUNT(DISTINCT(SOCIO)) AS TOTAL_CLIENTES_LY,
            SUM(TOTAL_VENTA_FIDELIZADA) AS TOTAL_VENTA_FIDELIZADA_LY
    FROM 
        TICKETS_LM_LY) AS B,
    (SELECT AVG(VENTAS) AS TICKET_PROMEDIO_FIDELIZADO_TY FROM (SELECT TICKET, SUM(VENTAS) AS VENTAS FROM DETALLADO_CLIENTES_TATA GROUP BY ALL)) AS C,
    (SELECT AVG(VENTAS) AS TICKET_PROMEDIO_FIDELIZADO_LY FROM (SELECT TICKET, SUM(VENTAS) AS VENTAS FROM DETALLADO_CLIENTES_TATA_24 GROUP BY ALL)) AS D;