WITH TICKET_PROMEDIO_FIDEL AS (
SELECT 
    YEAR(FT.TIEM_DIA_ID) ANIO,
    MONTH(FT.TIEM_DIA_ID) MES,
    ROUND( SUM(FT.VNTA_IMPORTE_SIN_IVA) / COUNT(DISTINCT FT.TICKET), 0 ) AS TICKET_PROMEDIO_FIDELIZADO
FROM 
    MSTRDB.DWH.FT_VENTAS AS FT
    JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON FT.TICKET = FFM.TICKET AND FFM.FDLN_MOVT_TIPO = 'RP'
    JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LG ON FT.GEOG_LOCL_ID = LG.GEOG_LOCL_ID
    JOIN MSTRDB.DWH.LU_GEOG_UNINEG AS LGU ON LG.GEOG_UNNG_ID = LGU.GEOG_UNNG_ID
WHERE 
    FT.TIEM_DIA_ID BETWEEN DATE_TRUNC(MONTH, DATEADD(MONTH, -23, CURRENT_DATE - 1)) AND LAST_DAY(DATEADD(MONTH, -1, CURRENT_DATE - 1))
    AND LGU.GEOG_UNNG_ID IN (2)
GROUP BY
    ALL
ORDER BY
    1, 2
)
,

TICKET_PROMEDIO_TATA AS (
SELECT 
    YEAR(FT.TIEM_DIA_ID) ANIO,
    MONTH(FT.TIEM_DIA_ID) MES,
    ROUND( SUM(FT.VNTA_IMPORTE_SIN_IVA) / COUNT(DISTINCT FT.TICKET), 0 ) AS TICKET_PROMEDIO_TATA
FROM 
    MSTRDB.DWH.FT_VENTAS AS FT
    JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LG ON FT.GEOG_LOCL_ID = LG.GEOG_LOCL_ID
    JOIN MSTRDB.DWH.LU_GEOG_UNINEG AS LGU ON LG.GEOG_UNNG_ID = LGU.GEOG_UNNG_ID
WHERE 
    FT.TIEM_DIA_ID BETWEEN DATE_TRUNC(MONTH, DATEADD(MONTH, -23, CURRENT_DATE - 1)) AND LAST_DAY(DATEADD(MONTH, -1, CURRENT_DATE - 1))
    AND LGU.GEOG_UNNG_ID IN (2)
GROUP BY
    ALL
ORDER BY
    1, 2
)

SELECT
    A.ANIO,
    A.MES,
    A.TICKET_PROMEDIO_FIDELIZADO,
    B.TICKET_PROMEDIO_TATA
FROM
    TICKET_PROMEDIO_FIDEL AS A
    INNER JOIN TICKET_PROMEDIO_TATA AS B ON A.ANIO = B.ANIO AND A.MES = B.MES;