WITH DATA AS (
    SELECT
        LDC.LOCAL,
        LDC.GEOG_LOCL_DESC,
        LDC.SOCI_SOCI_ID,
        CC.CLASIFICACION
    FROM
        SANDBOX_PLUS.DWH.CLASIFICACION_CLIENTES_SEMANA_V2 AS CC
        INNER JOIN SANDBOX_PLUS.DWH.LOCAL_DOMINANTE_CLIENTES AS LDC ON CC.SOCI_SOCI_ID = LDC.CLIE_TIPO_DOC || LDC.CLIE_CLIE_NDOC
    ORDER BY
        1,
        4
) 

SELECT
    LOCAL,
    GEOG_LOCL_DESC,
    CLASIFICACION AS CLASIFICACON_SOCIO,
    COUNT(DISTINCT(SOCI_SOCI_ID)) SOCIOS
FROM
    DATA
GROUP BY
    ALL
ORDER BY
    1,3;