WITH PARAMS AS (
    SELECT
        DATEADD('MONTH', -1, CURRENT_DATE()) AS INICIO_TY,
        CURRENT_DATE() - 1 AS FIN_TY,
        DATEADD('YEAR', -1, INICIO_TY) AS INICIO_LY,
        DATEADD('YEAR', -1, FIN_TY) AS FIN_LY
),
TICKETS_LM_TY AS (
    SELECT
        LGL.GEOG_LOCL_COD AS LOCAL,
        LGL.GEOG_LOCL_DESC AS DESC_LOCAL,
        FV.TICKET,
        CASE WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FFM.TICKET ELSE NULL END AS TICKET_FIDELIZADO,
        SUM(CASE WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FV.VNTA_IMPORTE_SIN_IVA ELSE 0 END) AS TOTAL_VENTA_FIDELIZADA,
        CASE WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FFM.SOCI_SOCI_ID ELSE NULL END AS SOCIO,
        SUM(CASE WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FV.VNTA_IMPORTE_SIN_IVA - (FV.VNTA_UNIDADES * FV.VNTA_COSTO_PROM_POND) ELSE 0 END) AS GB1_FIDELIZADO,
        SUM(CASE WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FV.VNTA_UNIDADES ELSE 0 END) AS UNIDADES_TICKET_FIDELIZADA
    FROM MSTRDB.DWH.FT_VENTAS AS FV
    INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FV.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
    LEFT JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON FV.TICKET = FFM.TICKET AND FFM.FDLN_MOVT_TIPO = 'RP'
    JOIN PARAMS AS P
    WHERE LGL.GEOG_UNNG_ID = 2
    AND FV.TIEM_DIA_ID BETWEEN P.INICIO_TY AND P.FIN_TY
    GROUP BY ALL
),
VENTAS_LM_TY AS (
    SELECT
        LOCAL, DESC_LOCAL,
        COUNT(DISTINCT(SOCIO)) AS SOCIOS_CONSUMIDORES_LM_TY,
        COUNT(DISTINCT(TICKET)) AS TICKETS_LM_TY,
        COUNT(DISTINCT(TICKET_FIDELIZADO)) AS TICKETS_FIDELIZADOS_LM_TY,
        ROUND((TICKETS_FIDELIZADOS_LM_TY / NULLIF(TICKETS_LM_TY, 0)) * 100, 2) AS PORC_TICK_FIDEL_TOTAL_TY,
        SUM(TOTAL_VENTA_FIDELIZADA) AS VENTA_FIDELIZADA_LM_TY,
        ROUND(SUM(GB1_FIDELIZADO), 2) AS TOTAL_GB1_LM_TY,
        ROUND((SUM(UNIDADES_TICKET_FIDELIZADA) / NULLIF(TICKETS_FIDELIZADOS_LM_TY, 0)), 2) AS UPT_25
    FROM TICKETS_LM_TY
    GROUP BY ALL
) 
,
TICKETS_LM_LY AS (
    SELECT
        LGL.GEOG_LOCL_COD AS LOCAL, LGL.GEOG_LOCL_DESC AS DESC_LOCAL, FV.TICKET,
        CASE WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FFM.TICKET ELSE NULL END AS TICKET_FIDELIZADO,
        SUM(CASE WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FV.VNTA_IMPORTE_SIN_IVA ELSE 0 END) AS TOTAL_VENTA_FIDELIZADA,
        CASE WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FFM.SOCI_SOCI_ID ELSE NULL END AS SOCIO,
        SUM(CASE WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FV.VNTA_IMPORTE_SIN_IVA - (FV.VNTA_UNIDADES * FV.VNTA_COSTO_PROM_POND) ELSE 0 END) AS GB1_FIDELIZADO,
        SUM(CASE WHEN FFM.SOCI_SOCI_ID IS NOT NULL THEN FV.VNTA_UNIDADES ELSE 0 END) AS UNIDADES_TICKET_FIDELIZADA
    FROM MSTRDB.DWH.FT_VENTAS AS FV
    INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FV.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
    LEFT JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON FV.TICKET = FFM.TICKET
    JOIN PARAMS AS P
    WHERE LGL.GEOG_UNNG_ID = 2
    AND FV.TIEM_DIA_ID BETWEEN P.INICIO_LY AND P.FIN_LY
    GROUP BY ALL
),
VENTAS_LM_LY AS (
    SELECT
        LOCAL, DESC_LOCAL,
        COUNT(DISTINCT(SOCIO)) AS SOCIOS_CONSUMIDORES_LM_LY,
        COUNT(DISTINCT(TICKET)) AS TICKETS_LM_LY,
        COUNT(DISTINCT(TICKET_FIDELIZADO)) AS TICKETS_FIDELIZADOS_LM_LY,
        ROUND((TICKETS_FIDELIZADOS_LM_LY / NULLIF(TICKETS_LM_LY, 0)) * 100, 2) AS PORC_TICK_FIDEL_TOTAL_LY,
        SUM(TOTAL_VENTA_FIDELIZADA) AS VENTA_FIDELIZADA_LM_LY,
        ROUND(SUM(GB1_FIDELIZADO), 2) AS TOTAL_GB1_LM_LY,
        ROUND((SUM(UNIDADES_TICKET_FIDELIZADA) / NULLIF(TICKETS_FIDELIZADOS_LM_LY, 0)), 2) AS UPT_24
    FROM TICKETS_LM_LY
    GROUP BY ALL
)
SELECT
    A.LOCAL, A.DESC_LOCAL,
    A.SOCIOS_CONSUMIDORES_LM_TY,
    ROUND((((A.SOCIOS_CONSUMIDORES_LM_TY / NULLIF(B.SOCIOS_CONSUMIDORES_LM_LY, 0)) - 1) * 100), 3) AS VAR_SOCIOS_25_VS_24,
    A.TICKETS_LM_TY,
    ROUND((((A.TICKETS_LM_TY / NULLIF(B.TICKETS_LM_LY, 0)) - 1) * 100), 3) AS VAR_TICKET_25_VS_24,
    A.TICKETS_FIDELIZADOS_LM_TY,
    ROUND((((A.TICKETS_FIDELIZADOS_LM_TY / NULLIF(B.TICKETS_FIDELIZADOS_LM_LY, 0)) - 1) * 100), 3) AS VAR_TICKET_FIDEL_25_VS_24,
    A.PORC_TICK_FIDEL_TOTAL_TY,
    ROUND((((A.PORC_TICK_FIDEL_TOTAL_TY / NULLIF(B.PORC_TICK_FIDEL_TOTAL_LY, 0)) - 1) * 100), 3) AS VAR_PORC_FIDEL_25_VS_24,
    A.VENTA_FIDELIZADA_LM_TY AS TOTAL_VTAS_FIDELIZADAS_TY,
    ROUND((((A.VENTA_FIDELIZADA_LM_TY / NULLIF(B.VENTA_FIDELIZADA_LM_LY, 0)) - 1) * 100), 3) AS VAR_VTAS_25_VS_24,
    A.UPT_25,
    ROUND((((A.UPT_25 / NULLIF(B.UPT_24, 0)) - 1) * 100), 3) AS VAR_UPT_25_VS_24
FROM
    VENTAS_LM_TY AS A
    LEFT JOIN VENTAS_LM_LY AS B ON A.LOCAL = B.LOCAL
ORDER BY
    A.LOCAL;